version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package
         --template-file trellothing.yaml \
         --s3-bucket bucket-name \
         --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - output.yaml
